#!/bin/sh -e
[ -z "${PREFIX}" ] && {
	echo "missing PREFIX"
}
prefix="${DESTDIR}${PREFIX}/lib"
echo "installing to" $prefix
for x in *.a; do
	install -D -m 644 $x "$prefix/$x"
done
for x in *crt*.o; do
	install -D -m 644 $x "$prefix/$x"
done
